In [6]:
import pickle
import numpy as np
import collections
import random
from sklearn.svm import SVC


#TODO try different kernels, find optimal parameters with cv


def getAAlst(helix):
    c = collections.Counter(helix)
    AA = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'H', 'I', 'G', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
    lst = []
    for aa in AA:
        lst.append(c[aa])
    return lst

#generate data
#this should be cleaned for U's
trans_hel = pickle.load(open("pdbtmhel", "rb"))
mol_hel = pickle.load(open("pdbhel", "rb"))

#makes sure that i can interpret the accuracy
trans_hel = trans_hel[:5000]
mol_hel = mol_hel[:5000]

data = []

for helix in trans_hel:
    temp = getAAlst(helix)
    temp.append(1)
    data.append(temp)

for helix in mol_hel:
    temp = getAAlst(helix)
    temp.append(-1)
    data.append(temp)

random.shuffle(data)       
npdata = np.array(data)

split = 2*len(npdata)//3

train = npdata[:split]
print(train)
test = npdata[split:]

X_train = train[:,0:20]
print(X_train)
Y_train = np.ravel(train[:,20:21])
X_test = test[:,0:20]
Y_test = np.ravel(test[:,20:21])


#svm
sv = SVC()

sv.fit(X_train, Y_train)
print(sv.score(X_test, Y_test))

[[ 2  0  0 ...  1  0 -1]
 [ 1  0  0 ...  0  2  1]
 [ 1  0  0 ...  2  4  1]
 ...
 [ 0  0  0 ...  0  1 -1]
 [ 6  0  0 ...  0  5  1]
 [ 0  1  0 ...  0  1  1]]
[[2 0 0 ... 1 1 0]
 [1 0 0 ... 0 0 2]
 [1 0 0 ... 3 2 4]
 ...
 [0 0 0 ... 0 0 1]
 [6 0 0 ... 1 0 5]
 [0 1 0 ... 0 0 1]]
0.9648622981956315
